name: Release Java library

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_REF: "${{ github.ref }}"

jobs:
  build_and_publish:
    name: Build jar library
    runs-on: ubuntu-latest
    steps:
      - name: Query app version number
        id: get_version
        shell: bash
        run: |
          echo "using app version ${GITHUB_REF:11}"
          echo "lib_version=${GITHUB_REF:11}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Gradle
        run: gradle build
        env:
          VERSION: ${{ env.lib_version }}
      - name: Publish package
        run: gradle clean build sign publish
        env:
          VERSION: ${{ env.lib_version }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
      - name: Approve Staged Repository Release
        run: gradle nexusStagingApprove
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}